// <auto-generated />
namespace ResumeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixentityandkeyphrasetoprofilerelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixentityandkeyphrasetoprofilerelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202005221800191_fix entity and keyphrase to profile relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
